# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ecos < Formula
  desc "ecos CLI orchestrates cloud FinOps workflows: project setup, resource provisioning, dbt workflow automation."
  homepage "https://github.com/ecos-labs/ecos"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ecos-labs/ecos/releases/download/v0.1.0/ecos-darwin-amd64.tar.gz"
      sha256 "f4ba3600905a700ae9080712ef8306b680feb8925feec5def53e5de49628f46c"

      def install
        bin.install "ecos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ecos-labs/ecos/releases/download/v0.1.0/ecos-darwin-arm64.tar.gz"
      sha256 "51cd154376e3d0c562b77987434850b292d04ac8fc4d599b49cbe54cd74d1314"

      def install
        bin.install "ecos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ecos-labs/ecos/releases/download/v0.1.0/ecos-linux-amd64.tar.gz"
      sha256 "7865f203467cbb410222d4f660cbb12b7aa626b53e911b147cb26f73fdf40099"
      def install
        bin.install "ecos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ecos-labs/ecos/releases/download/v0.1.0/ecos-linux-arm64.tar.gz"
      sha256 "46d8afe7f078dc21809bf3571f52fea7addbbf6fd9d272305c4ef27879debddd"
      def install
        bin.install "ecos"
      end
    end
  end

  test do
    system "#{bin}/ecos --version"
  end
end
