# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ecos < Formula
  desc "ecos CLI orchestrates cloud FinOps workflows: project setup, resource provisioning, dbt workflow automation."
  homepage "https://github.com/ecos-labs/ecos"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ecos-labs/ecos/releases/download/v0.2.0/ecos-darwin-amd64.tar.gz"
      sha256 "58114c740b89454d7b4586ea0e90b21575d69226e6452a1adc19dd17b4170d32"

      def install
        bin.install "ecos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ecos-labs/ecos/releases/download/v0.2.0/ecos-darwin-arm64.tar.gz"
      sha256 "9db6fabc32a645db5530be19501646aad83fec47d93c92e82706f1bed36d8783"

      def install
        bin.install "ecos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ecos-labs/ecos/releases/download/v0.2.0/ecos-linux-amd64.tar.gz"
      sha256 "8ffbf19cde1740488afd6949f67426cc8dc39b98badba253eeb0b0a0b29cb47b"
      def install
        bin.install "ecos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ecos-labs/ecos/releases/download/v0.2.0/ecos-linux-arm64.tar.gz"
      sha256 "69b1e7dfa5dca6da429cb97f2abc25aac8c70560771b33379d90063be8fcd85a"
      def install
        bin.install "ecos"
      end
    end
  end

  test do
    system "#{bin}/ecos --version"
  end
end
