# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ecos < Formula
  desc "ecos CLI orchestrates cloud FinOps workflows: project setup, resource provisioning, dbt workflow automation."
  homepage "https://github.com/ecos-labs/ecos"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ecos-labs/ecos/releases/download/v0.1.0/ecos-darwin-amd64.tar.gz"
      sha256 "0ca489bcc28b1ddd14a3d1bd22e624a20dc2bbd665ebf90f8445a22280fe1965"

      def install
        bin.install "ecos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ecos-labs/ecos/releases/download/v0.1.0/ecos-darwin-arm64.tar.gz"
      sha256 "053c84e28c7a6798699688b86082c0a4e2a8433c94d79a787f0667d669d16f63"

      def install
        bin.install "ecos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ecos-labs/ecos/releases/download/v0.1.0/ecos-linux-amd64.tar.gz"
      sha256 "9562196223d618cfac7baa41090f4a06311759974a5010042eb5efe98ac8130e"
      def install
        bin.install "ecos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ecos-labs/ecos/releases/download/v0.1.0/ecos-linux-arm64.tar.gz"
      sha256 "c5db9480351cfa9b9140f7d097153448f2ccbaa93764e7ae513a8bc7507d5d8a"
      def install
        bin.install "ecos"
      end
    end
  end

  test do
    system "#{bin}/ecos --version"
  end
end
