# This file was generated by GoReleaser. DO NOT EDIT.
cask "ecos" do
  name "ecos"
  desc "ecos CLI orchestrates cloud FinOps projects (AWS, Azure, GCP): setup, resource bootstrap, dbt-powered data transformation, and automation from the terminal."
  homepage "https://github.com/ecos-labs/ecos"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ecos"

  on_macos do
    on_intel do
      url "https://github.com/ecos-labs/ecos/releases/download/v#{version}/ecos-darwin-amd64.tar.gz",
        verified: "github.com/ecos-labs/ecos"
      sha256 "32bcc29a62c1d6b0582d60776a1324121372e1d95eab4e7fced365b83625eb79"
    end
    on_arm do
      url "https://github.com/ecos-labs/ecos/releases/download/v#{version}/ecos-darwin-arm64.tar.gz",
        verified: "github.com/ecos-labs/ecos"
      sha256 "ea25f68b7272b6f433676f88de0f53ae373e5bf5a00c54cbbd4e57ddc1a09c6e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ecos-labs/ecos/releases/download/v#{version}/ecos-darwin-amd64.tar.gz",
        verified: "github.com/ecos-labs/ecos"
      sha256 "527bbb77c456cb303fbbb0e19cfa20fed0a7fbeda0081d729e423edab073c9b6"
    end
    on_arm do
      url "https://github.com/ecos-labs/ecos/releases/download/v#{version}/ecos-darwin-arm64.tar.gz",
        verified: "github.com/ecos-labs/ecos"
      sha256 "61d73cdabe12e4da1fa638bdd4dcd2e812b231a93bd036dd0bf00352a80fd753"
    end
  end

  caveats do
    "Requires Python 3.8+ for dbt features."
    "On macOS, if you encounter a quarantine warning, run:"
    "  xattr -dr com.apple.quarantine /usr/local/bin/ecos"
  end

  # No zap stanza required
end
