# This file was generated by GoReleaser. DO NOT EDIT.
cask "ecos" do
  name "ecos"
  desc "ecos CLI orchestrates cloud FinOps projects (AWS, Azure, GCP): setup, resource bootstrap, dbt-powered data transformation, and automation from the terminal."
  homepage "https://github.com/ecos-labs/ecos"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ecos"

  on_macos do
    on_intel do
      url "https://github.com/ecos-labs/ecos/releases/download/v#{version}/ecos-darwin-amd64.tar.gz",
        verified: "github.com/ecos-labs/ecos"
      sha256 "0d2df3f72a225e25d833aec8d0cf43b76ac7b48684f69e628cabdfa3cc31fdba"
    end
    on_arm do
      url "https://github.com/ecos-labs/ecos/releases/download/v#{version}/ecos-darwin-arm64.tar.gz",
        verified: "github.com/ecos-labs/ecos"
      sha256 "5014f0579148d11c942f4621054fa4cff7413f5a67dc4155f68adee728d84fea"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ecos-labs/ecos/releases/download/v#{version}/ecos-darwin-amd64.tar.gz",
        verified: "github.com/ecos-labs/ecos"
      sha256 "3dc14be1acf2967afabc763bca56fe08237295ec8cf1045aaffa3e1efbdfa94a"
    end
    on_arm do
      url "https://github.com/ecos-labs/ecos/releases/download/v#{version}/ecos-darwin-arm64.tar.gz",
        verified: "github.com/ecos-labs/ecos"
      sha256 "9914c2596c4e5d4847e0ad203d69fc539f358f66527cf877a05770834aaed20b"
    end
  end

  caveats do
    "Requires Python 3.8+ for dbt features."
    "On macOS, if you encounter a quarantine warning, run:"
    "  xattr -dr com.apple.quarantine /usr/local/bin/ecos"
  end

  # No zap stanza required
end
