# This file was generated by GoReleaser. DO NOT EDIT.
cask "ecos" do
  name "ecos"
  desc "ecos CLI orchestrates cloud FinOps projects (AWS, Azure, GCP): setup, resource bootstrap, dbt-powered data transformation, and automation from the terminal."
  homepage "https://github.com/ecos-labs/ecos-core"
  version "0.6.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ecos"

  on_macos do
    on_intel do
      url "https://github.com/ecos-labs/ecos-core/releases/download/v#{version}/ecos-darwin-amd64.tar.gz",
        verified: "github.com/ecos-labs/ecos-core"
      sha256 "3116f2074fd2e9be36d510325b9dc7df0bbcb94ddd35720749dac75b2cb50c1f"
    end
    on_arm do
      url "https://github.com/ecos-labs/ecos-core/releases/download/v#{version}/ecos-darwin-arm64.tar.gz",
        verified: "github.com/ecos-labs/ecos-core"
      sha256 "858e464d9cf8ea0026fb05ebe1a472bcd1c5a65be1801947b59841849b3f0a52"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ecos-labs/ecos-core/releases/download/v#{version}/ecos-darwin-amd64.tar.gz",
        verified: "github.com/ecos-labs/ecos-core"
      sha256 "7f1d034f48cd9465d1fa396876f50e151b3d23485cec8b72ad699aed7570c56c"
    end
    on_arm do
      url "https://github.com/ecos-labs/ecos-core/releases/download/v#{version}/ecos-darwin-arm64.tar.gz",
        verified: "github.com/ecos-labs/ecos-core"
      sha256 "f58190a8c2d7bdfe2588ff9cb0b8a20f32e26e6734776935d24bcf7e81e6f258"
    end
  end

  caveats do
    "Requires Python 3.8+ for dbt features and the relevant cloud CLI for AWS/Azure/GCP automations."
    "On macOS, if you encounter the quarantine warning, run:"
    "  xattr -dr com.apple.quarantine /usr/local/bin/ecos"
  end

  # No zap stanza required
end
